id: c93a16df0b98466691b0ad0fb78a3fe6
initial_creation_type: ocr
source_metadata:
  volumes:
    54ffa484e9eb4624beac97d78316073c:
      base_file: v056.txt
      image_group_id: I1PD95902
      title: མ་རྟོགས་པ་རྟོགས་པར་བྱེད་པ་ཞེས་བྱ་བའི་རབ་ཏུ་བྱེད་པ།
      total_pages: 1605
      volume_number: 57
